/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_program_free: (a: number, b: number) => void;
export const program_to_internal: (a: any) => [number, number, number];
export const program_to: (a: any) => [number, number, number];
export const program_from_hex: (a: number, b: number) => [number, number, number];
export const program_null: () => [number, number, number];
export const program_sha256tree_internal: (a: any) => [number, number, number, number];
export const program_to_string_internal: (a: any) => [number, number, number];
export const program_as_pair_internal: (a: any) => [number, number, number];
export const program_listp_internal: (a: any) => [number, number, number];
export const program_nullp_internal: (a: any) => [number, number, number];
export const program_as_int_internal: (a: any) => [number, number, number];
export const program_as_bigint_internal: (a: any) => [number, number, number];
export const program_first_internal: (a: any) => [number, number, number];
export const program_rest_internal: (a: any) => [number, number, number];
export const program_cons_internal: (a: any, b: any) => [number, number, number];
export const program_run_internal: (a: any, b: any) => [number, number, number];
export const program_tuple_to_program_internal: (a: any) => [number, number, number];
export const program_as_bin_internal: (a: any) => [number, number, number, number];
export const program_list_len_internal: (a: any) => [number, number, number];
export const program_equal_to_internal: (a: any, b: any) => [number, number, number];
export const program_as_javascript_internal: (a: any) => [number, number, number];
export const program_curry_internal: (a: any, b: number, c: number) => [number, number, number];
export const program_uncurry_error_internal: (a: any) => [number, number, number, number];
export const program_uncurry_internal: (a: any) => [number, number, number, number];
export const create_clvm_runner: (a: number, b: number, c: any, d: any, e: any) => any;
export const final_value: (a: number) => any;
export const remove_clvm_runner: (a: number) => void;
export const run_step: (a: number) => any;
export const compile: (a: any, b: any, c: number, d: number) => any;
export const compose_run_function: (a: number, b: number, c: any, d: number, e: number) => any;
export const create_repl: () => number;
export const destroy_repl: (a: number) => void;
export const repl_run_string: (a: number, b: number, c: number) => any;
export const sexp_to_string: (a: any) => any;
export const h: (a: number, b: number) => [number, number, number, number];
export const t: (a: any, b: any) => [number, number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
