[package]
name = "clvm-risc0-test"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
risc0-zkvm = { version = "3.0.3", default-features = false, features = ["std", "client"] }
clvm_tools_rs = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }
borsh = { version = "1.5.7", features = ["derive"] }
hex = "0.4"

[build-dependencies]
risc0-build = "3.0.3"

[package.metadata.risc0]
methods = ["guest"]
