name: npm publish

on:
  push:
    branches:
      - base
  release:
    types: [published]
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main') && github.sha || '' }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build_npm:
    name: Npm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Env
        uses: Chia-Network/actions/setjobenv@main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up rusts
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: install wasm-pack
        run: cargo install --version 0.13.1 wasm-pack

      - name: wasm-pack build and pack
        run: wasm-pack build --release --target=nodejs wasm && wasm-pack pack wasm

      - name: Setup Node 24.x
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'

      - name: Test regression vs wasm artifact from 0.4.3 release
        run: |
          cargo test --features=preserved_043 random_cl26
